### ISSUE TITLE
Why the reshape and flatten in hw1?

### ISSUE THREAD

**Issue by alok** [txizzle/drl#1]
I noticed that you have the lines:

```python
X_train = X_train.reshape(X_train.shape[0], obs_data.shape[1], 1)
...

model.add(Dense(128, activation='relu', input_shape=(obs_data.shape[1], 1)))
model.add(Flatten())
```

Why do you make the array 3D only to almost immediately flatten it? I'm not really seeing the motivation.

**Comment by txizzle** [comment]
Good catch, it doesn't do anything as is. I think it's a relic from when I was playing around with different architectures / input formats. Thanks!
