### ISSUE TITLE
DAgger retraining

### ISSUE THREAD

**Issue by getaleks** [txizzle/drl#2]
Hi,

when running the DAgger algorithm, do you retrain the network with the current weights loaded or do you retrain "from scratch"?

The DAgger paper is not really clear about the practical implementation.

Thanks.

**Comment by txizzle** [comment]
Hi,

I believe either method is fine. See slide 7 of these [slides](http://rll.berkeley.edu/deeprlcourse-fa15/docs/2015.10.5.dagger.pdf).

I believe that training online with the current weights loaded might be more computationally efficient, as the current iteration of the policy should be a decent initial policy to finetune. However, this may be incorrect in some hard exploration environments, but even then I don't think it's terrible.

Cheers,
Ted

**Comment by getaleks** [comment]
Thanks for the response. Is there a difference in the training procedure when training on the current weights? Maybe training for less epochs? Seems to me that the model would be more inclined to overfit in this case, since the aggregated (new) data is a small percentage of the whole data set. So you are esentially training on most of the same data.

**Comment by txizzle** [comment]
The potential risk of overfitting is a good point. To counter that, more DAGGER iterations with fewer epochs for each iteration may work.

Overall, however, my understanding is that over time, the amount of expert data correcting for policy bias will increase relative to the whole data set - so the "training on most of the same data" point becomes less strong. I'd probably just recommend you play with these different schemes a bit (ie. re-train classifier every iteration, more or less epochs) and see what works for you. A lot of these decisions also depend on the difficulty of the environment.
